type ChapterMap = Record<string, Record<number, Record<string, string[]>>>;

export const CHAPTER_MAP: ChapterMap = {
  CBSE: {
    6: {
      Mathematics: ["Chapter 1: Knowing Our Numbers", "Chapter 2: Whole Numbers", "Chapter 3: Playing with Numbers", "Chapter 4: Basic Geometrical Ideas", "Chapter 5: Understanding Elementary Shapes", "Chapter 6: Integers", "Chapter 7: Fractions", "Chapter 8: Decimals", "Chapter 9: Data Handling", "Chapter 10: Mensuration", "Chapter 11: Algebra", "Chapter 12: Ratio and Proportion", "Chapter 13: Symmetry", "Chapter 14: Practical Geometry"],
      Science: ["Chapter 1: Food: Where Does It Come From?", "Chapter 2: Components of Food", "Chapter 3: Fibre to Fabric", "Chapter 4: Sorting Materials into Groups", "Chapter 5: Separation of Substances", "Chapter 6: Changes Around Us", "Chapter 7: Getting to Know Plants", "Chapter 8: Body Movements", "Chapter 9: The Living Organisms and Their Surroundings", "Chapter 10: Motion and Measurement of Distances", "Chapter 11: Light, Shadows and Reflections", "Chapter 12: Electricity and Circuits", "Chapter 13: Fun with Magnets", "Chapter 14: Water", "Chapter 15: Air Around Us", "Chapter 16: Garbage In, Garbage Out"],
      "Social Science": ["History Ch 1: What, Where, How and When?", "History Ch 2: From Hunting-Gathering to Growing Food", "History Ch 3: In the Earliest Cities", "History Ch 4: What Books and Burials Tell Us", "History Ch 5: Kingdoms, Kings and an Early Republic", "History Ch 6: New Questions and Ideas", "History Ch 7: Ashoka, The Emperor Who Gave Up War", "History Ch 8: Vital Villages, Thriving Towns", "History Ch 9: Traders, Kings and Pilgrims", "History Ch 10: New Empires and Kingdoms", "History Ch 11: Buildings, Paintings and Books", "Geography Ch 1: The Earth in the Solar System", "Geography Ch 2: Globe: Latitudes and Longitudes", "Geography Ch 3: Motions of the Earth", "Geography Ch 4: Maps", "Geography Ch 5: Major Domains of the Earth", "Geography Ch 6: Major Landforms of the Earth", "Geography Ch 7: Our Country — India", "Geography Ch 8: India: Climate, Vegetation and Wildlife", "Civics Ch 1: Understanding Diversity", "Civics Ch 2: Diversity and Discrimination", "Civics Ch 3: What is Government?", "Civics Ch 4: Key Elements of a Democratic Government", "Civics Ch 5: Panchayati Raj", "Civics Ch 6: Rural Administration", "Civics Ch 7: Urban Administration", "Civics Ch 8: Rural Livelihoods", "Civics Ch 9: Urban Livelihoods"],
      English: ["Unit 1: Who Did Patrick's Homework?", "Unit 2: How the Dog Found Himself a New Master!", "Unit 3: Taro's Reward", "Unit 4: An Indian — American Woman in Space", "Unit 5: A Different Kind of School", "Unit 6: Who I Am", "Unit 7: Fair Play", "Unit 8: A Game of Chance", "Unit 9: Desert Animals", "Unit 10: The Banyan Tree"],
    },
    7: {
      Mathematics: ["Chapter 1: Integers", "Chapter 2: Fractions and Decimals", "Chapter 3: Data Handling", "Chapter 4: Simple Equations", "Chapter 5: Lines and Angles", "Chapter 6: The Triangle and Its Properties", "Chapter 7: Congruence of Triangles", "Chapter 8: Comparing Quantities", "Chapter 9: Rational Numbers", "Chapter 10: Practical Geometry", "Chapter 11: Perimeter and Area", "Chapter 12: Algebraic Expressions", "Chapter 13: Exponents and Powers", "Chapter 14: Symmetry", "Chapter 15: Visualising Solid Shapes"],
      Science: ["Chapter 1: Nutrition in Plants", "Chapter 2: Nutrition in Animals", "Chapter 3: Fibre to Fabric", "Chapter 4: Heat", "Chapter 5: Acids, Bases and Salts", "Chapter 6: Physical and Chemical Changes", "Chapter 7: Weather, Climate and Adaptations of Animals to Climate", "Chapter 8: Winds, Storms and Cyclones", "Chapter 9: Soil", "Chapter 10: Respiration in Organisms", "Chapter 11: Transportation in Animals and Plants", "Chapter 12: Reproduction in Plants", "Chapter 13: Motion and Time", "Chapter 14: Electric Current and Its Effects", "Chapter 15: Light", "Chapter 16: Water: A Precious Resource", "Chapter 17: Forests: Our Lifeline", "Chapter 18: Wastewater Story"],
      "Social Science": ["History Ch 1: Tracing Changes Through a Thousand Years", "History Ch 2: New Kings and Kingdoms", "History Ch 3: The Delhi Sultans", "History Ch 4: The Mughal Empire", "History Ch 5: Rulers and Buildings", "History Ch 6: Towns, Traders and Craftspersons", "History Ch 7: Tribes, Nomads and Settled Communities", "History Ch 8: Devotional Paths to the Divine", "History Ch 9: The Making of Regional Cultures", "History Ch 10: Eighteenth-Century Political Formations", "Geography Ch 1: Environment", "Geography Ch 2: Inside Our Earth", "Geography Ch 3: Our Changing Earth", "Geography Ch 4: Air", "Geography Ch 5: Water", "Geography Ch 6: Natural Vegetation and Wildlife", "Geography Ch 7: Human Environment — Settlement, Transport and Communication", "Geography Ch 8: Human Environment Interactions — The Tropical and the Subtropical Region", "Geography Ch 9: Life in the Temperate Grasslands", "Geography Ch 10: Life in the Deserts", "Civics Ch 1: On Equality", "Civics Ch 2: Role of the Government in Health", "Civics Ch 3: How the State Government Works", "Civics Ch 4: Growing Up as Boys and Girls", "Civics Ch 5: Women Change the World", "Civics Ch 6: Understanding Media", "Civics Ch 7: Markets Around Us", "Civics Ch 8: A Shirt in the Market", "Civics Ch 9: Struggles for Equality"],
    },
    8: {
      Mathematics: ["Chapter 1: Rational Numbers", "Chapter 2: Linear Equations in One Variable", "Chapter 3: Understanding Quadrilaterals", "Chapter 4: Practical Geometry", "Chapter 5: Data Handling", "Chapter 6: Squares and Square Roots", "Chapter 7: Cubes and Cube Roots", "Chapter 8: Comparing Quantities", "Chapter 9: Algebraic Expressions and Identities", "Chapter 10: Visualising Solid Shapes", "Chapter 11: Mensuration", "Chapter 12: Exponents and Powers", "Chapter 13: Direct and Inverse Proportions", "Chapter 14: Factorisation", "Chapter 15: Introduction to Graphs", "Chapter 16: Playing with Numbers"],
      Science: ["Chapter 1: Crop Production and Management", "Chapter 2: Microorganisms: Friend and Foe", "Chapter 3: Synthetic Fibres and Plastics", "Chapter 4: Materials: Metals and Non-metals", "Chapter 5: Coal and Petroleum", "Chapter 6: Combustion and Flame", "Chapter 7: Conservation of Plants and Animals", "Chapter 8: Cell — Structure and Functions", "Chapter 9: Reproduction in Animals", "Chapter 10: Reaching the Age of Adolescence", "Chapter 11: Force and Pressure", "Chapter 12: Friction", "Chapter 13: Sound", "Chapter 14: Chemical Effects of Electric Current", "Chapter 15: Some Natural Phenomena", "Chapter 16: Light", "Chapter 17: Stars and the Solar System", "Chapter 18: Pollution of Air and Water"],
      "Social Science": ["History Ch 1: How, When and Where", "History Ch 2: From Trade to Territory", "History Ch 3: Ruling the Countryside", "History Ch 4: Tribals, Dikus and the Vision of a Golden Age", "History Ch 5: When People Rebel", "History Ch 6: Colonialism and the City", "History Ch 7: Weavers, Iron Smelters and Factory Owners", "History Ch 8: Civilising the Native, Educating the Nation", "History Ch 9: Women, Caste and Reform", "History Ch 10: The Changing World of Visual Arts", "History Ch 11: The Making of the National Movement", "History Ch 12: India After Independence", "Geography Ch 1: Resources", "Geography Ch 2: Land, Soil, Water, Natural Vegetation and Wildlife Resources", "Geography Ch 3: Mineral and Power Resources", "Geography Ch 4: Agriculture", "Geography Ch 5: Industries", "Geography Ch 6: Human Resources", "Civics Ch 1: The Indian Constitution", "Civics Ch 2: Understanding Secularism", "Civics Ch 3: Why Do We Need a Parliament?", "Civics Ch 4: Understanding Laws", "Civics Ch 5: Judiciary", "Civics Ch 6: Understanding Our Criminal Justice System", "Civics Ch 7: Understanding Marginalisation", "Civics Ch 8: Confronting Marginalisation", "Civics Ch 9: Public Facilities", "Civics Ch 10: Law and Social Justice"],
    },
    9: {
      Mathematics: ["Chapter 1: Number Systems", "Chapter 2: Polynomials", "Chapter 3: Coordinate Geometry", "Chapter 4: Linear Equations in Two Variables", "Chapter 5: Introduction to Euclid's Geometry", "Chapter 6: Lines and Angles", "Chapter 7: Triangles", "Chapter 8: Quadrilaterals", "Chapter 9: Areas of Parallelograms and Triangles", "Chapter 10: Circles", "Chapter 11: Constructions", "Chapter 12: Heron's Formula", "Chapter 13: Surface Areas and Volumes", "Chapter 14: Statistics", "Chapter 15: Probability"],
      Science: ["Chapter 1: Matter in Our Surroundings", "Chapter 2: Is Matter Around Us Pure?", "Chapter 3: Atoms and Molecules", "Chapter 4: Structure of the Atom", "Chapter 5: The Fundamental Unit of Life", "Chapter 6: Tissues", "Chapter 7: Diversity in Living Organisms", "Chapter 8: Motion", "Chapter 9: Force and Laws of Motion", "Chapter 10: Gravitation", "Chapter 11: Work and Energy", "Chapter 12: Sound", "Chapter 13: Why Do We Fall Ill?", "Chapter 14: Natural Resources", "Chapter 15: Improvement in Food Resources"],
      "Social Science": ["History Ch 1: The French Revolution", "History Ch 2: Socialism in Europe and the Russian Revolution", "History Ch 3: Nazism and the Rise of Hitler", "History Ch 4: Forest Society and Colonialism", "History Ch 5: Pastoralists in the Modern World", "Geography Ch 1: India — Size and Location", "Geography Ch 2: Physical Features of India", "Geography Ch 3: Drainage", "Geography Ch 4: Climate", "Geography Ch 5: Natural Vegetation and Wildlife", "Geography Ch 6: Population", "Civics Ch 1: Democracy in the Contemporary World", "Civics Ch 2: What is Democracy? Why Democracy?", "Civics Ch 3: Constitutional Design", "Civics Ch 4: Electoral Politics", "Civics Ch 5: Working of Institutions", "Civics Ch 6: Democratic Rights", "Economics Ch 1: The Story of Village Palampur", "Economics Ch 2: People as Resource", "Economics Ch 3: Poverty as a Challenge", "Economics Ch 4: Food Security in India"],
    },
    10: {
      Science: ["Chapter 1: Chemical Reactions and Equations", "Chapter 2: Acids, Bases and Salts", "Chapter 3: Metals and Non-metals", "Chapter 4: Carbon and its Compounds", "Chapter 5: Periodic Classification of Elements", "Chapter 6: Life Processes", "Chapter 7: Control and Coordination", "Chapter 8: How do Organisms Reproduce?", "Chapter 9: Heredity and Evolution", "Chapter 10: Light — Reflection and Refraction", "Chapter 11: Human Eye and Colourful World", "Chapter 12: Electricity", "Chapter 13: Magnetic Effects of Electric Current", "Chapter 14: Sources of Energy", "Chapter 15: Our Environment", "Chapter 16: Sustainable Management of Natural Resources"],
      Mathematics: ["Chapter 1: Real Numbers", "Chapter 2: Polynomials", "Chapter 3: Pair of Linear Equations in Two Variables", "Chapter 4: Quadratic Equations", "Chapter 5: Arithmetic Progressions", "Chapter 6: Triangles", "Chapter 7: Coordinate Geometry", "Chapter 8: Introduction to Trigonometry", "Chapter 9: Some Applications of Trigonometry", "Chapter 10: Circles", "Chapter 11: Constructions", "Chapter 12: Areas Related to Circles", "Chapter 13: Surface Areas and Volumes", "Chapter 14: Statistics", "Chapter 15: Probability"],
      "Social Science": ["History Ch 1: The Rise of Nationalism in Europe", "History Ch 2: Nationalism in India", "History Ch 3: The Making of a Global World", "History Ch 4: The Age of Industrialisation", "History Ch 5: Print Culture and the Modern World", "Geography Ch 1: Resources and Development", "Geography Ch 2: Forest and Wildlife Resources", "Geography Ch 3: Water Resources", "Geography Ch 4: Agriculture", "Geography Ch 5: Minerals and Energy Resources", "Geography Ch 6: Manufacturing Industries", "Geography Ch 7: Lifelines of National Economy", "Civics Ch 1: Power Sharing", "Civics Ch 2: Federalism", "Civics Ch 3: Democracy and Diversity", "Civics Ch 4: Gender, Religion and Caste", "Civics Ch 5: Popular Struggles and Movements", "Civics Ch 6: Political Parties", "Civics Ch 7: Outcomes of Democracy", "Civics Ch 8: Challenges to Democracy", "Economics Ch 1: Development", "Economics Ch 2: Sectors of the Indian Economy", "Economics Ch 3: Money and Credit", "Economics Ch 4: Globalisation and the Indian Economy", "Economics Ch 5: Consumer Rights"],
      English: ["Chapter 1: A Letter to God", "Chapter 2: Nelson Mandela: Long Walk to Freedom", "Chapter 3: Two Stories about Flying", "Chapter 4: From the Diary of Anne Frank", "Chapter 5: The Hundred Dresses I", "Chapter 6: The Hundred Dresses II", "Chapter 7: Glimpses of India", "Chapter 8: Mijbil the Otter", "Chapter 9: Madam Rides the Bus", "Chapter 10: The Sermon at Benares", "Chapter 11: The Proposal"],
      Hindi: ["Kshitij Ch 1: Surdas", "Kshitij Ch 2: Tulsidas", "Kshitij Ch 3: Dev", "Kshitij Ch 4: Jaishankar Prasad", "Kshitij Ch 5: Suryakant Tripathi Nirala", "Kshitij Ch 6: Nagarjun", "Kshitij Ch 7: Girija Kumar Mathur", "Kshitij Ch 8: Rituraj", "Kshitij Ch 9: Manglesh Dabral", "Kshitij Ch 10: Swayam Prakash", "Kshitij Ch 11: Ramvriksha Benipuri", "Kshitij Ch 12: Yashpal", "Kshitij Ch 13: Sarveshwar Dayal Saxena", "Kshitij Ch 14: Mannu Bhandari", "Kshitij Ch 15: Mahaveer Prasad Dwivedi", "Kshitij Ch 16: Yatindra Mishra", "Kshitij Ch 17: Bhagwan Das"],
    },
    11: {
      Physics: ["Chapter 1: Physical World", "Chapter 2: Units and Measurements", "Chapter 3: Motion in a Straight Line", "Chapter 4: Motion in a Plane", "Chapter 5: Laws of Motion", "Chapter 6: Work, Energy and Power", "Chapter 7: System of Particles and Rotational Motion", "Chapter 8: Gravitation", "Chapter 9: Mechanical Properties of Solids", "Chapter 10: Mechanical Properties of Fluids", "Chapter 11: Thermal Properties of Matter", "Chapter 12: Thermodynamics", "Chapter 13: Kinetic Theory", "Chapter 14: Oscillations", "Chapter 15: Waves"],
      Chemistry: ["Chapter 1: Some Basic Concepts of Chemistry", "Chapter 2: Structure of Atom", "Chapter 3: Classification of Elements and Periodicity in Properties", "Chapter 4: Chemical Bonding and Molecular Structure", "Chapter 5: States of Matter", "Chapter 6: Thermodynamics", "Chapter 7: Equilibrium", "Chapter 8: Redox Reactions", "Chapter 9: Hydrogen", "Chapter 10: The s-Block Elements", "Chapter 11: The p-Block Elements", "Chapter 12: Organic Chemistry — Some Basic Principles and Techniques", "Chapter 13: Hydrocarbons", "Chapter 14: Environmental Chemistry"],
      Mathematics: ["Chapter 1: Sets", "Chapter 2: Relations and Functions", "Chapter 3: Trigonometric Functions", "Chapter 4: Principle of Mathematical Induction", "Chapter 5: Complex Numbers and Quadratic Equations", "Chapter 6: Linear Inequalities", "Chapter 7: Permutations and Combinations", "Chapter 8: Binomial Theorem", "Chapter 9: Sequences and Series", "Chapter 10: Straight Lines", "Chapter 11: Conic Sections", "Chapter 12: Introduction to Three Dimensional Geometry", "Chapter 13: Limits and Derivatives", "Chapter 14: Mathematical Reasoning", "Chapter 15: Statistics", "Chapter 16: Probability"],
      Biology: ["Chapter 1: The Living World", "Chapter 2: Biological Classification", "Chapter 3: Plant Kingdom", "Chapter 4: Animal Kingdom", "Chapter 5: Morphology of Flowering Plants", "Chapter 6: Anatomy of Flowering Plants", "Chapter 7: Structural Organisation in Animals", "Chapter 8: Cell: The Unit of Life", "Chapter 9: Biomolecules", "Chapter 10: Cell Cycle and Cell Division", "Chapter 11: Transport in Plants", "Chapter 12: Mineral Nutrition", "Chapter 13: Photosynthesis in Higher Plants", "Chapter 14: Respiration in Plants", "Chapter 15: Plant Growth and Development", "Chapter 16: Digestion and Absorption", "Chapter 17: Breathing and Exchange of Gases", "Chapter 18: Body Fluids and Circulation", "Chapter 19: Excretory Products and their Elimination", "Chapter 20: Locomotion and Movement", "Chapter 21: Neural Control and Coordination", "Chapter 22: Chemical Coordination and Integration"],
    },
    12: {
      Physics: ["Chapter 1: Electric Charges and Fields", "Chapter 2: Electrostatic Potential and Capacitance", "Chapter 3: Current Electricity", "Chapter 4: Moving Charges and Magnetism", "Chapter 5: Magnetism and Matter", "Chapter 6: Electromagnetic Induction", "Chapter 7: Alternating Current", "Chapter 8: Electromagnetic Waves", "Chapter 9: Ray Optics and Optical Instruments", "Chapter 10: Wave Optics", "Chapter 11: Dual Nature of Radiation and Matter", "Chapter 12: Atoms", "Chapter 13: Nuclei", "Chapter 14: Semiconductor Electronics"],
      Chemistry: ["Chapter 1: The Solid State", "Chapter 2: Solutions", "Chapter 3: Electrochemistry", "Chapter 4: Chemical Kinetics", "Chapter 5: Surface Chemistry", "Chapter 6: General Principles and Processes of Isolation of Elements", "Chapter 7: The p-Block Elements", "Chapter 8: The d and f Block Elements", "Chapter 9: Coordination Compounds", "Chapter 10: Haloalkanes and Haloarenes", "Chapter 11: Alcohols, Phenols and Ethers", "Chapter 12: Aldehydes, Ketones and Carboxylic Acids", "Chapter 13: Amines", "Chapter 14: Biomolecules"],
      Mathematics: ["Chapter 1: Relations and Functions", "Chapter 2: Inverse Trigonometric Functions", "Chapter 3: Matrices", "Chapter 4: Determinants", "Chapter 5: Continuity and Differentiability", "Chapter 6: Application of Derivatives", "Chapter 7: Integrals", "Chapter 8: Application of Integrals", "Chapter 9: Differential Equations", "Chapter 10: Vector Algebra", "Chapter 11: Three Dimensional Geometry", "Chapter 12: Linear Programming", "Chapter 13: Probability"],
      Biology: ["Chapter 1: Reproduction in Organisms", "Chapter 2: Sexual Reproduction in Flowering Plants", "Chapter 3: Human Reproduction", "Chapter 4: Reproductive Health", "Chapter 5: Principles of Inheritance and Variation", "Chapter 6: Molecular Basis of Inheritance", "Chapter 7: Evolution", "Chapter 8: Human Health and Disease", "Chapter 9: Strategies for Enhancement in Food Production", "Chapter 10: Microbes in Human Welfare", "Chapter 11: Biotechnology: Principles and Processes", "Chapter 12: Biotechnology and its Applications", "Chapter 13: Organisms and Populations", "Chapter 14: Ecosystem", "Chapter 15: Biodiversity and Conservation", "Chapter 16: Environmental Issues"],
      Accountancy: ["Chapter 1: Accounting for Not-for-Profit Organisation", "Chapter 2: Accounting for Partnership: Basic Concepts", "Chapter 3: Reconstitution of a Partnership Firm — Admission of a Partner", "Chapter 4: Reconstitution of a Partnership Firm — Retirement/Death of a Partner", "Chapter 5: Dissolution of Partnership Firm", "Chapter 6: Accounting for Share Capital", "Chapter 7: Issue and Redemption of Debentures", "Chapter 8: Financial Statements of a Company", "Chapter 9: Analysis of Financial Statements", "Chapter 10: Accounting Ratios", "Chapter 11: Cash Flow Statement"],
      "Business Studies": ["Chapter 1: Nature and Significance of Management", "Chapter 2: Principles of Management", "Chapter 3: Business Environment", "Chapter 4: Planning", "Chapter 5: Organising", "Chapter 6: Staffing", "Chapter 7: Directing", "Chapter 8: Controlling", "Chapter 9: Financial Management", "Chapter 10: Financial Markets", "Chapter 11: Marketing Management", "Chapter 12: Consumer Protection"],
      Economics: ["Chapter 1: Introduction", "Chapter 2: Theory of Consumer Behaviour", "Chapter 3: Production and Costs", "Chapter 4: The Theory of the Firm under Perfect Competition", "Chapter 5: Market Equilibrium", "Chapter 6: Non-competitive Markets", "Macro Ch 1: Introduction to Macroeconomics", "Macro Ch 2: National Income Accounting", "Macro Ch 3: Money and Banking", "Macro Ch 4: Determination of Income and Employment", "Macro Ch 5: Government Budget and the Economy", "Macro Ch 6: Open Economy Macroeconomics"],
    },
  },
  GSEB: {
    9: {
      Vigyan: ["Prarambh 1: Dravyanu Anukranaman", "Prarambh 2: Dravyanu Shudhikaranam", "Prarambh 3: Paramaanu ane Anukrao", "Prarambh 4: Paramaanuni Rachna", "Prarambh 5: Jivananu Mool Ekok — Kosh", "Prarambh 6: Peshiyo", "Prarambh 7: Jivsrushtimaani Vividhata", "Prarambh 8: Gati", "Prarambh 9: Bal ane Gaatino Niyamo", "Prarambh 10: Gurutvakarshan", "Prarambh 11: Karya ane Urja", "Prarambh 12: Dhvani", "Prarambh 13: Aapane Kem Bimari Lage Chhe?", "Prarambh 14: Prakrutik Sansadhano", "Prarambh 15: Khadyan Sudharma"],
      Ganit: ["Prarambh 1: Sankhya Paddhati", "Prarambh 2: Bahupadio", "Prarambh 3: Nirdeshank Bhoomiti", "Prarambh 4: Be Chalrashio Samaghataio", "Prarambh 5: Yuklid Bhoomitino Parichay", "Prarambh 6: Rekhao ane Kono", "Prarambh 7: Trikono", "Prarambh 8: Chaturbhujao", "Prarambh 9: Vartullo", "Prarambh 10: Heron Sutra", "Prarambh 11: Parishtha Kshetra ane Khadkam", "Prarambh 12: Aankado", "Prarambh 13: Sambhavana"],
    },
    10: {
      Vigyan: ["Adhyay 1: Rasayanik Prakriya ane Samikaranao", "Adhyay 2: Amla, Kshar ane Khar", "Adhyay 3: Dhatu ane Adhatu", "Adhyay 4: Carbon ane Teni Sanyojano", "Adhyay 5: Tatvonu Ayojannu Aavartik Vargikaranam", "Adhyay 6: Jivannu Kriyao", "Adhyay 7: Niyantran ane Samanvay", "Adhyay 8: Jivadhariyo Kem Prajanan Kare Chhe?", "Adhyay 9: Vaarasagat ane Vikash", "Adhyay 10: Prakash — Paraavartam ane Apavartan", "Adhyay 11: Manav Netram ane Rangbheri Duniya", "Adhyay 12: Viddyut", "Adhyay 13: Viddyut Prawaahni Chumbakiy Asaro", "Adhyay 14: Urjana Strotao", "Adhyay 15: Aapanou Paryavaran", "Adhyay 16: Prakrutik Sansadhanannu Tkaao"],
      Ganit: ["Adhyay 1: Vaasatavic Sankhyao", "Adhyay 2: Bahupadio", "Adhyay 3: Be Chalrashionu Jugma Samaghato", "Adhyay 4: Dvidhati Samaghato", "Adhyay 5: Samantar Shreni", "Adhyay 6: Trikono", "Adhyay 7: Nirdeshank Bhoomiti", "Adhyay 8: Trigonometri — Parichay", "Adhyay 9: Trigonometrini Anukramanio", "Adhyay 10: Vartullo", "Adhyay 11: Raachan", "Adhyay 12: Vartul Sathi Sambandhit Kshetrafal", "Adhyay 13: Parishtha Kshetra ane Khadkam", "Adhyay 14: Aankado", "Adhyay 15: Sambhavana"],
      "Samajik Vigyan": ["Itihas 1: Yurop maa Rashtriyavad", "Itihas 2: Bharatmaa Rashtriyavad", "Itihas 3: Vaishvik Viswanu Nirman", "Itihas 4: Audyogikaran yug", "Itihas 5: Chapkam Sanskriti", "Bhugol 1: Sansadhano ane Vikas", "Bhugol 2: Van ane Vanyajiv Sansadhano", "Bhugol 3: Jal Sansadhano", "Bhugol 4: Krishi", "Bhugol 5: Khanij ane Urja Sansadhano", "Bhugol 6: Utpadak Kshetro", "Bhugol 7: Rashtriy Arthatantranu Jivanrektao", "Rajniti 1: Satta Bhaagidari", "Rajniti 2: Sanghvaad", "Rajniti 3: Loktantra ane Vividhata", "Rajniti 4: Linging Dharm ane Jati", "Arthshastr 1: Vikas", "Arthshastr 2: Bharatiy Arthatantranu Kshetro"],
    },
    11: {
      "Bhautik Vigyan": ["Prarambh 1: Bhautikshastr Jagat", "Prarambh 2: Maap ane Ekamo", "Prarambh 3: Sadhi Rekhama Gati", "Prarambh 4: Satahmaa Gati", "Prarambh 5: Gaatina Niyamo", "Prarambh 6: Karya Urja ane Shakti", "Prarambh 7: Kanikao Paddhati", "Prarambh 8: Gurutvakarshan", "Prarambh 9: Kathhos Dravy Gundharmao", "Prarambh 10: Pravaahi Dravy Gundharmao", "Prarambh 11: Taapiy Gundharmao", "Prarambh 12: Ushnagatiki", "Prarambh 13: Kineitic Sidhdhant", "Prarambh 14: Dolano", "Prarambh 15: Moujao"],
      "Rasayan Vigyan": ["Prarambh 1: Rasayanashastrna Mool Kalpano", "Prarambh 2: Paramaanuni Rachna", "Prarambh 3: Tatvo Vargikaranam", "Prarambh 4: Rasayanik Bandhan", "Prarambh 5: Dravy Avastha", "Prarambh 6: Ushnagatiki", "Prarambh 7: Samtolana", "Prarambh 8: Rediox Prakriyao", "Prarambh 9: Udajaan", "Prarambh 10: s-Bhaagno Tatvo", "Prarambh 11: p-Bhaagno Tatvo", "Prarambh 12: Karbon Sarkhana Kaarbhanik Rasayan", "Prarambh 13: Hidrokarbano", "Prarambh 14: Paryavaran Rasayan"],
      Ganit: ["Prarambh 1: Samucho", "Prarambh 2: Sambandho ane Sarvagrao", "Prarambh 3: Trigonometric Sarvagrao", "Prarambh 4: Ganit Anumaan Sidhdhaant", "Prarambh 5: Samishta Sankhyao", "Prarambh 6: Rekhiya Asamamaantrao", "Prarambh 7: Kramchay ane Sangrachay", "Prarambh 8: Dvipad Pramax", "Prarambh 9: Shredi ane Shrenkiao", "Prarambh 10: Sadhi Rekhaao", "Prarambh 11: Shankuchedao", "Prarambh 12: Triy Parimaani Bhoomiti", "Prarambh 13: Maaryada ane Avakalan", "Prarambh 14: Aankado", "Prarambh 15: Sambhavana"],
    },
    12: {
      "Bhautik Vigyan": ["Adhyay 1: Viddyut Bharao ane Khetrao", "Adhyay 2: Viddyut Stitimaanki", "Adhyay 3: Viddyut Pravaah", "Adhyay 4: Gatimaaan Bharao", "Adhyay 5: Chumbaktv", "Adhyay 6: Viddyutchumbakiy Prarana", "Adhyay 7: Antikrami Prawaah", "Adhyay 8: Viddyutchumbakiy Moujao", "Adhyay 9: Kirno Prakaashashastr", "Adhyay 10: Mouj Prakaashashastr", "Adhyay 11: Vikirananuu Dvivid Svabhav", "Adhyay 12: Paramaanuo", "Adhyay 13: Nabhik", "Adhyay 14: Arddhavahak Viddyutashastr"],
      "Rasayan Vigyan": ["Adhyay 1: Dradh Avastha", "Adhyay 2: Ghaol", "Adhyay 3: Viddyut Rasaayan", "Adhyay 4: Rasayanik Gaatikayi", "Adhyay 5: Parishth Rasaayan", "Adhyay 6: Tatv Alag Karvani Prakriyao", "Adhyay 7: p-Bhagno Tatvo", "Adhyay 8: d ane f Bhagno Tatvo", "Adhyay 9: Sanyojano", "Adhyay 10: Haloalken ane Halovaren", "Adhyay 11: Maddiraa ane Itr", "Adhyay 12: Aldehydes, Ketones ane Karboxilic Amla", "Adhyay 13: Amins", "Adhyay 14: Jeevvaijnanik Ano"],
      Ganit: ["Adhyay 1: Sambandho ane Sarvagrao", "Adhyay 2: Viparit Trigonometric Sarvagrao", "Adhyay 3: Maatriko", "Adhyay 4: Saranio", "Adhyay 5: Satatataa ane Avakalniyata", "Adhyay 6: Avakalno Upayog", "Adhyay 7: Samakalan", "Adhyay 8: Samakalano Upayog", "Adhyay 9: Avakali Samaghato", "Adhyay 10: Sadia Bijganit", "Adhyay 11: Triy Parimaani Bhoomiti", "Adhyay 12: Rekhiy Aayojan", "Adhyay 13: Sambhavana"],
    },
  },
};

export function getSubjects(board: string, classLevel: number): string[] {
  const boardMap = CHAPTER_MAP[board];
  if (!boardMap) return [];
  const classMap = boardMap[classLevel];
  if (!classMap) return [];
  return Object.keys(classMap);
}

export function getChapters(board: string, classLevel: number, subject: string): string[] {
  const boardMap = CHAPTER_MAP[board];
  if (!boardMap) return [];
  const classMap = boardMap[classLevel];
  if (!classMap) return [];
  return classMap[subject] ?? [];
}

export const TOPIC_SUGGESTIONS: Record<string, string[]> = {
  Mathematics: ["Real Numbers", "Polynomials", "Quadratic Equations", "Arithmetic Progressions", "Triangles (Similarity)", "Coordinate Geometry", "Trigonometric Identities", "Heights and Distances", "Circles and Tangents", "Statistics (Mean/Median/Mode)", "Probability", "Integration by Substitution", "Matrices and Determinants", "Limits and Continuity", "Vectors", "Permutations and Combinations"],
  Science: ["Chemical Reactions", "Acids Bases Salts", "Metals and Non-Metals", "Carbon Compounds", "Life Processes (Nutrition/Respiration)", "Heredity and Evolution", "Reflection and Refraction", "Electricity (Ohm's Law)", "Magnetic Effects of Current", "Human Eye", "Photosynthesis", "Human Reproductive System", "Newton's Laws of Motion", "Work Energy Theorem", "Sound Waves"],
  Physics: ["Electric Field and Potential", "Capacitance", "Current Electricity (Kirchhoff's Laws)", "Moving Charges (Lorentz Force)", "Electromagnetic Induction (Faraday's Law)", "AC Circuits (LCR)", "Ray Optics (Lens/Mirror)", "Photoelectric Effect", "Radioactivity", "Semiconductor Devices"],
  Chemistry: ["Solid State (Crystal Structures)", "Colligative Properties", "Electrochemical Cells", "Rate Law and Order of Reaction", "Adsorption (Freundlich Isotherm)", "Coordination Compounds (Nomenclature)", "Haloalkanes (SN1/SN2)", "Aldehydes and Ketones (Nucleophilic Addition)", "Amines (Basicity)", "DNA Structure and Replication"],
  Biology: ["Photosynthesis (Light Reactions)", "Respiration (Krebs Cycle)", "DNA Replication", "Mendelian Genetics", "Evolution (Natural Selection)", "Immune System", "Hormones and Endocrine System", "Ecosystem and Food Web", "Biotechnology (PCR, ELISA)"],
  "Social Science": ["French Revolution", "Nationalism in India (1857–1947)", "Industrial Revolution", "Globalisation", "Democracy and Diversity", "Federalism in India", "Electoral Politics", "Money and Banking", "Consumer Rights", "Resources and Development"],
};
