name: Mobile Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mobile/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Mobile App
      working-directory: ./mobile
      run: |
        npm install
        npm run build
