name: Web Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - 'web/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Web
      working-directory: ./web
      run: |
        npm install
        npm run build
